### PR TITLE
Bug/item image

### PR DESCRIPTION
**Pull request by ric-ram**
Fix missing images when no item images were detected by pointing to placeholder image location when the condition was true.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks ric-ram, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Some issues need to be fixed before you can merge your PR:
 - Looks like you run npm install, but we're using yarn. Please remove "frontend/package-lock.json" from your PR and use yarn instead.

**Review by ric-ram — COMMENTED** [review]
File removed as requested

**Review by vanessa-cooper — APPROVED** [review]
Excellent job ric-ram! You're now able to merge the PR.

**Pull request merged**
