### PR TITLE
Fix no image url when creating a new item

### PR DESCRIPTION
**Pull request by ric-ram**
Fixed the broken image when the user does not add an image URL when creating a new item.

image

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks ric-ram, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by ric-ram — COMMENTED** [review]
Apply requested changes

**Review by ric-ram — COMMENTED** [review]
Reviewed changes

**Pull request closed without merging**
